apiVersion: pipecd.dev/v1beta1
kind: CloudRunApp
spec:
  name: canary-app
  pipeline:
    stages:
      - name: CLOUDRUN_PROMOTE
        with:
          percent: 10
      - name: WAIT
        with:
          duration: 5s
      - name: CLOUDRUN_PROMOTE
        with:
          percent: 50
      - name: WAIT
        with:
          duration: 5s
      - name: CLOUDRUN_PROMOTE
        with:
          percent: 100
  description: |
    This app demonstrates how to deploy a Cloud Run application with Canary.
