apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  # FIXME: Replace here with your piped ID.
  pipedID: feee18ec-3207-493c-9f1d-112d1fd5b9b4
  # Base64 encoded string of the piped private key.
  # FIXME: Replace here with your piped base64 key.
  pipedKeyData: anB1ODNjazVhdjd1bXNlYmFxaGhtbHRmaDE3ZmhlNnF6dDg0ZXJkZGFnbThlcWd3MXI=
  # Write in a format like "host:443" because the communication is done via gRPC.
  # FIXME: Replace here with your piped address if you connect Piped to a control plane that does not run locally.
  apiAddress: localhost:8080
  repositories:
  - repoId: CD
    remote: git@github.com:niladrix719/CD.git
    branch: main
  syncInterval: 1m
  platformProviders:
  - name: my-cloudrun
    type: CLOUDRUN
    config:
      project: groovy-height-404319
      region: europe-west1
